name: Any - Push - Docker Compose Test

on: push

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
      TF_LOG: DEBUG

    defaults:
      run:
        working-directory: ./deployments/docker-compose
    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d

      - name: Test
        run: bash docker-compose.tests.sh
