name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
      TF_LOG: DEBUG

    defaults:
      run:
        working-directory: ./deployments
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

